import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {readFile,lstat} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {CHARACTER_ACTIONS,CHARACTER_FILES,CHARACTER_LABELS} from '../public/character-actions.js';
import {storeImage} from './media.mjs';
const script=fileURLToPath(new URL('../scripts/validate-character.py',import.meta.url));
export function characterConceptBrief(role,brief=''){return `第一阶段：为「${role.name}」（${role.title}）根据第一张照片设计一个像素画风人物。第二张图片仅为现有办公室人物的画风参考，不要复制其中人物身份。保留照片中的脸型、发型、眼镜等辨识特征。用户要求：${brief||'保留照片人物的服装特征'}。
只交付一张人物定稿 character-concept.png 和简短的 character-concept.md（相似特征、服装配色、真实生图来源和查看验证结果）。必须使用真实图片生成工具，像素画风：清晰像素块、阶梯状轮廓、有限色板、游戏精灵比例，不要照片滤镜、光滑矢量图、3D渲染。单个完整全身站姿，正面略转向右，头发到鞋都完整且四周留白，无道具、桌椅、文字、拼图或多视图。可使用干净纯色背景；本阶段不要求透明通道或512尺寸，不画棋盘格。图片生成后必须实际查看，与原照片及画风参考比对。不要制作动作素材；此图需由董事长预览确认后才能进入第二阶段。不要因为等待董事长确认而不交付定稿；先完成这张图的生成、保存和自身验收。`;}
export {spriteSheetSteps as characterActionSteps} from './sprite-sheets.mjs';
export function approvedConcept(role,id){const concept=role.characterConcepts?.find(c=>c.id===id&&c.validated);if(!concept?.approvedAt)throw Error('请先预览并确认人物定稿');if(concept.referenceImage!==role.referenceImage)throw Error('参考图已更换，请重新设计并确认人物');return concept;}
export async function importCharacterConcept(cwd,mediaDir,{referenceImage,brief,projectId}){const file=path.join(cwd,'character-concept.png');const st=await lstat(file);if(!st.isFile()||st.isSymbolicLink()||st.size>8*1024*1024)throw Error('人物定稿必须是小于8MB的真实PNG文件');await promisify(execFile)(process.env.ONE_PC_PYTHON||'python3',['-c',"from PIL import Image; import sys; im=Image.open(sys.argv[1]); assert im.format=='PNG' and min(im.size)>=128 and max(im.size)<=4096, 'Expected a complete PNG concept'; im.verify()",file]);const image=await storeImage('data:image/png;base64,'+(await readFile(file)).toString('base64'),mediaDir);return {id:randomUUID(),image,referenceImage,brief,projectId,createdAt:Date.now(),validated:true};}
export function characterBrief(role,brief,files=CHARACTER_FILES){return `为「${role.name}」（${role.title}）按附带参考图制作完整卡通游戏角色动作包。用户设计要求：${brief||'保留人物身份、发型和服装特征，与温暖像素办公室一致'}。必须使用真实图片生成工具，不得用代码绘图或提示词充当图片。文件直接保存到工作目录，严格命名：${files.join('、')}。共 ${files.length} 张 512×512 透明 PNG，每张仅一个完整角色，四周至少 8px 留白，脚/椅轮落地点在 y=480～490，画面中间，动作间大小一致。所有动作头部和躯干的实际像素尺寸保持一致，不能为了让坐姿铺满画布而放大人物；所有动作保持同一身份和服装，不能复制一张静态图冒充不同动作。idle 站立两帧；walk-right 朝右连贯三帧（朝左由窗口镜像）；walk-up 背面朝上三帧；walk-down 正面朝下三帧；seated 普通工位左后方视角朝右敲键盘两帧；董事长身体整体朝画面下方，微微向右转25度，以正面为主的四分之三坐姿，眼睛看向前方稍右的电脑；phone/music/read/game 与椅子保持相同角度，绝不可朝后面的窗户；主管和财务保持正面坐姿，${['boss','manager','finance'].includes(role.id)?'不包含椅子（场景提供独立办公室椅子）':'包含黑色办公椅'}、完整腿和鞋但不包含桌子；phone 相同坐姿手握手机且屏幕朝角色；game 坐姿手握游戏手柄；music 坐姿自然听音乐，不画耳机或额外设备，不拿手机；drink 站立单手杯子由胸前举到嘴边；sofa 坐姿无椅子，朝右（榻榻米朝左时镜像）；sofa-front 严格正面朝向画面下方坐姿，无椅子；greet 站立挥手；sit 从站立到坐下的两帧含椅子；pull 站立伸手拉椅子的两帧，椅子由场景提供不要画进帧里；read 坐姿阅读两帧；chat 站立交谈两帧。身体、手臂、腿不可断开，不能裁头，手中物体真实连接。每张动作必须不同。结束前用图片查看工具逐张检查所有帧、人物一致性、朝向、肢体连接和坐姿；没有可用生图能力或无法完成所有帧时明确报告未完成，不要声称成功。`;}
export async function importCharacterPack(cwd,mediaDir){const {stdout}=await promisify(execFile)(process.env.ONE_PC_PYTHON||'python3',[script,cwd,JSON.stringify(CHARACTER_FILES)],{maxBuffer:1024*1024,timeout:60000});const geometry=JSON.parse(stdout),frames={};for(const [action,count] of Object.entries(CHARACTER_ACTIONS)){frames[action]=[];for(let i=0;i<count;i++){const key=`${action}-${i}.png`,bytes=await readFile(path.join(cwd,key));const name=await storeImage('data:image/png;base64,'+bytes.toString('base64'),mediaDir);frames[action].push({name,...geometry[key]});}}return {id:randomUUID(),frames,createdAt:Date.now(),validated:true};}

export async function validateCharacterFrames(cwd,files){await promisify(execFile)(process.env.ONE_PC_PYTHON||'python3',[script,cwd,JSON.stringify(files)],{maxBuffer:1024*1024,timeout:60000});}
