import { randomUUID } from 'node:crypto';
export const BASE_ROLES = [
 {id:'manager',title:'主管',name:'阿程',color:'#718b67',skill:'项目统筹 · 任务调度',duty:'拆解需求、协调岗位、汇总成果'},
 {id:'product',title:'产品策划',name:'小知',color:'#d4a252',skill:'需求研究 · 产品文案',duty:'研究资料、整理需求与验收标准'},
 {id:'designer',title:'设计总监',name:'米朵',color:'#bd7897',skill:'UI 设计 · 图像创作',duty:'界面设计、图片创作和视觉素材'},
 {id:'developer',title:'开发工程师',name:'阿码',color:'#688fab',skill:'代码编写 · 功能实现',duty:'代码实现、接口与故障修复'},
 {id:'reviewer',title:'审核经理',name:'小严',color:'#9a8abb',skill:'测试验收 · 质量检查',duty:'独立检查产物与需求，反馈问题'},
 {id:'delivery',title:'交付经理',name:'小舟',color:'#bb875c',skill:'打包归档 · 交付说明',duty:'整理产物、打包与交付文档'},
 {id:'hr',title:'HR',name:'小麦',color:'#c28765',skill:'人才招聘 · Skill 配置',duty:'招聘专业角色、管理技能和工位'},
 {id:'finance',title:'财务总监',name:'金豆',color:'#6a9c92',skill:'Token 统计 · 收支管理',duty:'用量核算、记账与财务分析'}
];
export const createState=()=>({version:1,boss:{id:'boss',title:'董事长',name:'你',status:'idle',color:'#bba269',skill:'提出需求 · 决策验收',duty:'公司的老板，向主管提出需求并决定方向'},roles:BASE_ROLES.map(r=>({...r,status:'idle',activity:'休息中'})),projects:[],usage:[],entries:[],events:[],mode:'live'});
export function log(s,text,role='manager',kind='info'){s.events.unshift({id:randomUUID(),time:Date.now(),text,role,kind});s.events=s.events.slice(0,100);}
export function addUsage(s,id,role,u,projectId=null){if(!u||s.usage.some(x=>x.id===id))return;const input=u.input_tokens,output=u.output_tokens;if(!Number.isSafeInteger(input)||input<0||!Number.isSafeInteger(output)||output<0)return;s.usage.push({id,role,projectId,input,output,cached:Math.max(0,u.cached_input_tokens||0),total:input+output,time:Date.now(),source:'codex.exec'});}
export function recruit(s,{title,skillId},skills){title=String(title||'').trim();if(!title||title.length>16)throw Error('职称需要 1～16 个字符');const old=s.roles.find(r=>r.title===title);if(old)return old;const skill=skills.find(x=>x.id===skillId);if(!skill)throw Error('请选择已发现的本地 Skill');if(s.roles.length>=20)throw Error('本版最多展示 20 个岗位');const role={id:'hire-'+randomUUID().slice(0,8),title,name:title,color:'#ae8e5b',skill:skill.name,skillId:skill.id,skillPath:skill.path,duty:skill.description||skill.name,status:'idle',activity:'已入职 · 等待任务'};s.roles.push(role);log(s,`新同事「${title}」已入职，已绑定 ${skill.name}`,'hr');return role;}
export function addEntry(s,e){const amount=Number(e.amount);if(!Number.isFinite(amount)||amount<=0||amount>1e10)throw Error('金额必须是有效正数');if(!['income','expense'].includes(e.type))throw Error('收支类型无效');if(!['CNY','USD','EUR'].includes(e.currency))throw Error('请选择币种');if(!['confirmed','pending'].includes(e.status))throw Error('请选择已确认或待确认');const entry={id:randomUUID(),minor:Math.round(amount*100),type:e.type,currency:e.currency,status:e.status,note:String(e.note||'').slice(0,200),time:Date.now(),projectId:e.projectId||null};s.entries.push(entry);return entry;}
export function progress(p){if(!p?.steps?.length)return 0;let all=p.steps.reduce((n,x)=>n+x.weight,0);let done=p.steps.filter(x=>x.status==='verified').reduce((n,x)=>n+x.weight,0);return p.steps.every(x=>x.status==='verified')?(p.source==='workbuddy'&&p.status!=='completed'?99:100):Math.min(99,Math.round(done/all*100));}
export function validatePlan(p,roles){if(!Array.isArray(p.steps)||!p.steps.length||p.steps.length>10)throw Error('计划需要 1～10 个步骤');for(const step of p.steps){if(!roles.some(r=>r.id===step.role)||['manager','hr','reviewer'].includes(step.role))throw Error('计划包含不可执行岗位');if(!Number.isFinite(step.weight)||step.weight<=0||step.weight>10)throw Error('步骤权重无效');if(!step.title||typeof step.instructions!=='string'||!step.instructions.trim())throw Error('步骤缺少任务描述');}return p;}
