import {deploymentCompanyName} from '../lib/company.mjs';
import {createInterface} from 'node:readline/promises';
import {parseArgs} from 'node:util';import {spawn,execFile} from 'node:child_process';import {promisify} from 'node:util';import {readFile,writeFile,mkdir,copyFile,access} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {findCodex} from '../lib/platform.mjs';import {installationRoot as root,showOffice,deployment} from '../lib/local-launch.mjs';
const exec=promisify(execFile);
const {values:v}=parseArgs({options:{company:{type:'string'},mode:{type:'string',default:'web'},autostart:{type:'string',default:'agent'},bind:{type:'string',default:'workbuddy'},port:{type:'string',default:'4317'},'dry-run':{type:'boolean'},'no-open':{type:'boolean'}}});
if(!['web','app'].includes(v.mode)||!['agent','off'].includes(v.autostart))throw Error('Use --mode web|app --autostart agent|off');
const agents=v.bind==='none'?[]:v.bind.split(',');if(agents.some(a=>!['codex','workbuddy'].includes(a)))throw Error('Use --bind codex,workbuddy|none');const port=Number(v.port);if(!Number.isInteger(port)||port<1024||port>65535)throw Error('Port must be 1024..65535');if(Number(process.versions.node.split('.')[0])<24)throw Error('Install Node.js 24 or later');
const previous=await deployment();
let savedCompany;try{savedCompany=JSON.parse(await readFile(path.join(root,'.local/office.json'),'utf8')).company?.name;}catch(e){if(e.code!=='ENOENT')throw e;}
let companyName=savedCompany||previous.companyName;
if(v.company!==undefined){companyName=deploymentCompanyName(v.company);if(savedCompany&&savedCompany!==companyName)throw Error('此办公室已有名称，请点击左上角公司名称修改；部署不会覆盖已有设置。');}
if(!companyName){if(!process.stdin.isTTY)throw Error('部署前请询问用户：公司叫什么 OPC？然后加上 --company "用户的名字" 重新部署。');const question=createInterface({input:process.stdin,output:process.stdout});try{companyName=deploymentCompanyName(await question.question('你的公司叫什么 OPC？（输入名字，如 小林）：'));}finally{question.close();}}
const config={companyName,mode:v.mode,autostart:v.autostart,agents:agents.length?agents:(previous.agents?.length?previous.agents:['codex','workbuddy']),port},mcp={command:process.execPath,args:[path.join(root,'opc-mcp.mjs')]};
if(v['dry-run']){console.log(JSON.stringify({root,config,mcp,platform:process.platform,windowsStatus:'not-device-verified'},null,2));process.exit(0);}
const local=path.join(root,'.local');await mkdir(local,{recursive:true});
// Validate and back up the existing config before any binding changes. Never replace unrelated servers.
let wbFile,wbConfig;if(agents.includes('workbuddy')){wbFile=path.join(process.env.OPC_WORKBUDDY_HOME||path.join(os.homedir(),'.workbuddy'),'mcp.json');try{wbConfig=JSON.parse(await readFile(wbFile,'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;wbConfig={mcpServers:{}};}if(wbConfig.mcpServers!==undefined&&(!wbConfig.mcpServers||Array.isArray(wbConfig.mcpServers)||typeof wbConfig.mcpServers!=='object'))throw Error('Unexpected WorkBuddy MCP config');const old=wbConfig.mcpServers?.['opc-office'];if(old&&JSON.stringify(old)!==JSON.stringify(mcp))throw Error('WorkBuddy already has a different opc-office binding; inspect it before replacing');}
const codex=agents.includes('codex')?findCodex():null;if(agents.includes('codex')&&!codex)throw Error('Codex not found; install/login or choose --bind workbuddy');
await writeFile(path.join(local,'deployment.json'),JSON.stringify(config,null,2),{mode:0o600});await writeFile(path.join(local,'node-path.txt'),process.execPath);await writeFile(path.join(local,'mcp-config.json'),JSON.stringify({mcpServers:{'opc-office':mcp}},null,2),{mode:0o600});
if(v.mode==='app'){if(process.platform==='darwin')await exec('/bin/bash',[path.join(root,'scripts/build-macos.sh')],{cwd:root,maxBuffer:1024*1024});else if(process.platform==='win32')await exec('powershell.exe',['-NoProfile','-File',path.join(root,'scripts/build-windows.ps1')],{cwd:root,windowsHide:true});else throw Error('App mode requires macOS or Windows');}
if(wbFile){await mkdir(path.dirname(wbFile),{recursive:true});await copyFile(wbFile,wbFile+'.opc-backup-'+Date.now()).catch(e=>{if(e.code!=='ENOENT')throw e;});wbConfig.mcpServers??={};wbConfig.mcpServers['opc-office']=mcp;await writeFile(wbFile,JSON.stringify(wbConfig,null,2),{mode:0o600});}
if(codex){let old;try{const r=await exec(codex,['mcp','get','opc-office','--json']);old=JSON.parse(r.stdout);}catch(e){if(!/not found|No MCP server/i.test(String(e.stderr||e.message)))throw e;}if(old&&(old.transport?.command!==mcp.command||JSON.stringify(old.transport?.args)!==JSON.stringify(mcp.args)))throw Error('Codex already has another opc-office binding; inspect it first');if(!old)await exec(codex,['mcp','add','opc-office','--',mcp.command,...mcp.args]);}
const xml=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
if(process.platform==='darwin'){
 const legacy=path.join(os.homedir(),'Library/LaunchAgents/local.onepc.follow-host.plist');const legacyText=await readFile(legacy,'utf8').catch(()=>'');if(legacyText.includes(xml(root))){await exec('launchctl',['bootout','gui/'+process.getuid(),legacy]).catch(()=>{});const {unlink}=await import('node:fs/promises');await unlink(legacy);}
 const file=path.join(os.homedir(),'Library/LaunchAgents/local.opc.agent-start.plist');let old;try{old=await readFile(file,'utf8');}catch(e){if(e.code!=='ENOENT')throw e;}if(old&&!old.includes(xml(root)))throw Error('Another OPC installation owns the startup entry');
 if(old)await exec('launchctl',['bootout','gui/'+process.getuid(),file]).catch(()=>{});
 if(v.autostart==='agent'){await mkdir(path.dirname(file),{recursive:true});await writeFile(file,`<?xml version="1.0"?><plist version="1.0"><dict><key>Label</key><string>local.opc.agent-start</string><key>ProgramArguments</key><array><string>${xml(process.execPath)}</string><string>${xml(path.join(root,'scripts/watch-agents.mjs'))}</string></array><key>RunAtLoad</key><true/><key>KeepAlive</key><true/><key>StandardErrorPath</key><string>${xml(path.join(local,'autostart.log'))}</string></dict></plist>`);await exec('launchctl',['bootstrap','gui/'+process.getuid(),file]);}else if(old){const {unlink}=await import('node:fs/promises');await unlink(file);}
}else if(process.platform==='win32'){
 const file=path.join(process.env.APPDATA,'Microsoft/Windows/Start Menu/Programs/Startup/OPC-agent-start.vbs');let old;try{old=await readFile(file,'utf8');}catch(e){if(e.code!=='ENOENT')throw e;}if(old&&!old.includes(root.replaceAll('"','""')))throw Error('Another OPC installation owns the startup entry');
 if(v.autostart==='agent'){await mkdir(path.dirname(file),{recursive:true});const command='"'+process.execPath+'" "'+path.join(root,'scripts/watch-agents.mjs')+'"';await writeFile(file,'CreateObject("WScript.Shell").Run "'+command.replaceAll('"','""')+'", 0, False\r\n');}else if(old){const {unlink}=await import('node:fs/promises');await unlink(file);}
}
if(process.platform==='win32'&&v.autostart==='agent'){const child=spawn(process.execPath,[path.join(root,'scripts/watch-agents.mjs')],{detached:true,windowsHide:true,stdio:'ignore'});child.unref();}
if(!v['no-open'])await showOffice(root);
console.log(JSON.stringify({installed:true,config,entry:v.mode==='app'?path.join(root,'dist',process.platform==='darwin'?'OPC.app':'OPC.exe'):path.join(root,'scripts/launch.mjs'),binding:'Restart or reload MCP in your Agent; first login and OS permission remain interactive',autostart:process.platform==='win32'?'Startup watcher takes effect after next Windows sign-in; MCP can start OPC on load':'configured'},null,2));
